# Generated by Django 4.0.3 on 2022-04-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0002_alter_getstarted_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getstarted',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
