# Generated by Django 4.0.4 on 2022-05-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0005_topteammembers_remove_whatmakeusdifferent1_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusstarting',
            options={'verbose_name': 'Starting text for About us page', 'verbose_name_plural': 'Starting text for About us page'},
        ),
        migrations.AlterModelOptions(
            name='companystat',
            options={'verbose_name': 'company stats', 'verbose_name_plural': 'company stats'},
        ),
        migrations.AlterModelOptions(
            name='datasecuritysection',
            options={'verbose_name': 'Data Security Section', 'verbose_name_plural': 'Data Security Section'},
        ),
        migrations.AlterModelOptions(
            name='footerdata',
            options={'verbose_name': 'Footer Section', 'verbose_name_plural': 'Footer Section'},
        ),
        migrations.AlterModelOptions(
            name='getstarted',
            options={'verbose_name': 'Service page Get started Form', 'verbose_name_plural': 'Service page Get started Form'},
        ),
        migrations.AlterModelOptions(
            name='homepagefront',
            options={'verbose_name': 'home page front section', 'verbose_name_plural': 'home page front section'},
        ),
        migrations.AlterModelOptions(
            name='howdoesitworkhome',
            options={'verbose_name': 'how does it work for home page', 'verbose_name_plural': 'how does it work for home page'},
        ),
        migrations.AlterModelOptions(
            name='howdowework',
            options={'verbose_name': 'How do we work', 'verbose_name_plural': 'How do we work'},
        ),
        migrations.AlterModelOptions(
            name='letsdoit',
            options={'verbose_name': 'Contact us section', 'verbose_name_plural': 'Contact us section'},
        ),
        migrations.AlterModelOptions(
            name='membersdetailnpic',
            options={'verbose_name': 'Team Members details and pictures', 'verbose_name_plural': 'Team Members details and pictures'},
        ),
        migrations.AlterModelOptions(
            name='ourservicefront',
            options={'verbose_name': 'Service page Front text', 'verbose_name_plural': 'Service page Front text'},
        ),
        migrations.AlterModelOptions(
            name='ourteamintro',
            options={'verbose_name': 'Our Team Introduction', 'verbose_name_plural': 'Our Team Introduction'},
        ),
        migrations.AlterModelOptions(
            name='ourworkslide',
            options={'verbose_name': 'Our Work Slide', 'verbose_name_plural': 'Our Work Slide'},
        ),
        migrations.AlterModelOptions(
            name='servicecard',
            options={'verbose_name': 'Service cards slide data', 'verbose_name_plural': 'Service cards slide data'},
        ),
        migrations.AlterModelOptions(
            name='technologiesicons',
            options={'verbose_name': 'Technologies icon', 'verbose_name_plural': 'Technologies icon'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonials section', 'verbose_name_plural': 'Testimonials section'},
        ),
        migrations.AlterModelOptions(
            name='topteammembers',
            options={'verbose_name': 'Top Team Member details', 'verbose_name_plural': 'Top Team Member details'},
        ),
        migrations.AlterModelOptions(
            name='whatdoweoffer',
            options={'verbose_name': 'What do we offer text', 'verbose_name_plural': 'What do we offer text'},
        ),
        migrations.AlterModelOptions(
            name='whatmakeusdifferent1',
            options={'verbose_name': 'What makes us different (first)', 'verbose_name_plural': 'What makes us different (first)'},
        ),
        migrations.AlterModelOptions(
            name='whatmakeusdifferent2',
            options={'verbose_name': 'What makes us different (second)', 'verbose_name_plural': 'What makes us different (second)'},
        ),
    ]
