# Generated by Django 4.0.4 on 2022-05-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0006_alter_aboutusstarting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusstarting',
            options={'verbose_name': 'Starting text for About us page (ABOUT US PAGE)', 'verbose_name_plural': 'Starting text for About us page (ABOUT US PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='companystat',
            options={'verbose_name': 'company stats (SERVICE PAGE)', 'verbose_name_plural': 'company stats (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='datasecuritysection',
            options={'verbose_name': 'Data Security Section (SERVICE PAGE)', 'verbose_name_plural': 'Data Security Section (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='footerdata',
            options={'verbose_name': 'Footer Section (FOOTER PAGE)', 'verbose_name_plural': 'Footer Section (FOOTER PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='getstarted',
            options={'verbose_name': 'Service page Get started Form (SERVICE PAGE)', 'verbose_name_plural': 'Service page Get started Form (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='homepagefront',
            options={'verbose_name': 'home page front section (HOME PAGE)', 'verbose_name_plural': 'home page front section (HOME PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='howdoesitworkhome',
            options={'verbose_name': 'how does it work for home page (HOME PAGE)', 'verbose_name_plural': 'how does it work for home page (HOME PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='howdowework',
            options={'verbose_name': 'How do we work (SERVICE PAGE)', 'verbose_name_plural': 'How do we work (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='letsdoit',
            options={'verbose_name': 'Contact us section (ABOUT US PAGE)', 'verbose_name_plural': 'Contact us section (ABOUT US PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='membersdetailnpic',
            options={'verbose_name': 'Team Members details and pictures (TEAM PAGE)', 'verbose_name_plural': 'Team Members details and pictures (TEAM PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='ourservicefront',
            options={'verbose_name': 'Service page Front text (SERVICE PAGE)', 'verbose_name_plural': 'Service page Front text (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='ourteamintro',
            options={'verbose_name': 'Our Team Introduction (TEAM PAGE)', 'verbose_name_plural': 'Our Team Introduction (TEAM PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='ourworkslide',
            options={'verbose_name': 'Our Work Slide (SERVICE PAGE)', 'verbose_name_plural': 'Our Work Slide (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='servicecard',
            options={'verbose_name': 'Service cards slide data (SERVICE PAGE)', 'verbose_name_plural': 'Service cards slide data (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='technologiesicons',
            options={'verbose_name': 'Technologies icon (SERVICE PAGE)', 'verbose_name_plural': 'Technologies icon (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonials section (SERVICE PAGE)', 'verbose_name_plural': 'Testimonials section (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='topteammembers',
            options={'verbose_name': 'Top Team Member details (ABOUT US PAGE)', 'verbose_name_plural': 'Top Team Member details (ABOUT US PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='whatdoweoffer',
            options={'verbose_name': 'What do we offer text (SERVICE PAGE)', 'verbose_name_plural': 'What do we offer text (SERVICE PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='whatmakeusdifferent1',
            options={'verbose_name': 'What makes us different (first) (ABOUT US PAGE)', 'verbose_name_plural': 'What makes us different (first) (ABOUT US PAGE)'},
        ),
        migrations.AlterModelOptions(
            name='whatmakeusdifferent2',
            options={'verbose_name': 'What makes us different (second) (ABOUT US PAGE)', 'verbose_name_plural': 'What makes us different (second) (ABOUT US PAGE)'},
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='card_pic',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
        migrations.AlterField(
            model_name='technologiesicons',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
    ]
