# Generated by Django 4.0.4 on 2022-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0008_alter_technologiesicons_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourworkslide',
            name='card_class',
            field=models.CharField(blank=True, choices=[('laptop', 'fa fa-laptop'), ('paper plane', 'fa fa-paper-plane-o'), ('line chart', 'fa fa-line-chart'), ('visual box', 'fa fa-object-group'), ('hard drive', 'fa fa-hdd-o')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='technologiesicons',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='technologies/'),
        ),
    ]
