# Generated by Django 4.0.4 on 2022-05-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0009_ourworkslide_card_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworkslide',
            name='card_class',
            field=models.CharField(blank=True, choices=[('fa fa-laptop', 'laptop'), ('fa fa-paper-plane-o', 'paper plane'), ('fa fa-line-chart', 'line chart'), ('fa fa-object-group', 'visual box'), ('fa fa-hdd-o', 'hard drive')], max_length=300, null=True),
        ),
    ]
