# Generated by Django 4.0.4 on 2022-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0010_alter_ourworkslide_card_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystat',
            name='data_speed',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
