# Generated by Django 4.0.4 on 2022-05-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0011_companystat_data_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystat',
            name='data_speed',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='data_speed in seconds'),
        ),
    ]
