# Generated by Django 4.0.4 on 2022-05-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0013_servicecard_card_class_alter_ourworkslide_card_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdetailnpic',
            name='member_pic',
            field=models.ImageField(upload_to='team_member'),
        ),
        migrations.AlterField(
            model_name='topteammembers',
            name='member_pic',
            field=models.ImageField(upload_to='team_member'),
        ),
    ]
