# Generated by Django 4.0.4 on 2022-05-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0014_alter_membersdetailnpic_member_pic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembersDetailnPic',
        ),
        migrations.AlterModelOptions(
            name='ourteamintro',
            options={'verbose_name': 'Team Members details and pictures (TEAM PAGE)', 'verbose_name_plural': 'Team Members details and pictures (TEAM PAGE)'},
        ),
    ]
