# Generated by Django 4.0.4 on 2022-05-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0015_delete_membersdetailnpic_alter_ourteamintro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourteamintro',
            options={'verbose_name': 'Our Team Introduction (TEAM PAGE)', 'verbose_name_plural': 'Our Team Introduction (TEAM PAGE)'},
        ),
        migrations.AddField(
            model_name='homepagefront',
            name='top_heading',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
