# Generated by Django 4.0.4 on 2022-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetec', '0017_careerintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Career selection Section (Career PAGE)',
                'verbose_name_plural': 'Career selection Section (Career PAGE)',
            },
        ),
    ]
